apiVersion: v1
kind: Service
metadata:
  name: cv-tensorboard-service
spec:
  ports:
  - port: 80
    targetPort: 6006
  selector:
    app: cv-tensorboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-tensorboard
  labels:
    app: cv-tensorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-tensorboard
  template:
    metadata:
      labels:
        app: cv-tensorboard
    spec:
      containers:
        - name: cv-tensorboard
          image: tensorflow/tensorflow
          command: ["tensorboard", "--logdir=/pvc/logs/cv03", "--host", "0.0.0.0"]
          ports:
          -  containerPort: 6006
          resources:
            requests:
              cpu: "0.01"
            limits:
              memory: "4G"
          volumeMounts:
            - name: cv-pvc
              mountPath: /pvc
      volumes:
        - name: cv-pvc
          persistentVolumeClaim:
            claimName: cv-pvc
      imagePullSecrets:
        - name: private-registry-auth
